import { SampleCase } from "./types";

export const SAMPLE_CASES: SampleCase[] = [
  {
    id: "SAMPLE-01",
    label: "Wrong transfer with matching evidence",
    input: {
      ticket_id: "TKT-001",
      complaint: "I sent 5000 taka to a wrong number around 2pm today. The number was supposed to be 01712345678 but I think I typed it wrong. The person isn't responding to my call. Please help me get my money back.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      campaign_context: "boishakh_bonanza_day_1",
      transaction_history: [
        { transaction_id: "TXN-9101", timestamp: "2026-04-14T14:08:22Z", type: "transfer", amount: 5000, counterparty: "+8801719876543", status: "completed" },
        { transaction_id: "TXN-9087", timestamp: "2026-04-13T18:12:00Z", type: "cash_in", amount: 10000, counterparty: "AGENT-512", status: "completed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-001",
      relevant_transaction_id: "TXN-9101",
      evidence_verdict: "consistent",
      case_type: "wrong_transfer",
      severity: "high",
      department: "dispute_resolution",
      agent_summary: "Customer reports sending 5000 BDT via TXN-9101 to +8801719876543, which they now believe was the wrong recipient.",
      recommended_next_action: "Verify TXN-9101 details with the customer and initiate the wrong-transfer dispute workflow per policy.",
      customer_reply: "We have noted your concern about transaction TXN-9101. Please do not share your PIN or OTP with anyone. Our dispute team will review the case and contact you through official support channels.",
      human_review_required: true,
      confidence: 0.9,
      reason_codes: ["wrong_transfer", "transaction_match"],
    },
    rationale: "Complaint amount (5000) and approximate time (2pm) align cleanly with TXN-9101.",
  },
  {
    id: "SAMPLE-02",
    label: "Wrong transfer claim with inconsistent evidence",
    input: {
      ticket_id: "TKT-002",
      complaint: "I sent 2000 to the wrong person by mistake. Please reverse it.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9202", timestamp: "2026-04-14T11:30:00Z", type: "transfer", amount: 2000, counterparty: "+8801812345678", status: "completed" },
        { transaction_id: "TXN-9180", timestamp: "2026-04-10T09:15:00Z", type: "transfer", amount: 2500, counterparty: "+8801812345678", status: "completed" },
        { transaction_id: "TXN-9145", timestamp: "2026-04-05T17:45:00Z", type: "transfer", amount: 1500, counterparty: "+8801812345678", status: "completed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-002",
      relevant_transaction_id: "TXN-9202",
      evidence_verdict: "inconsistent",
      case_type: "wrong_transfer",
      severity: "medium",
      department: "dispute_resolution",
      agent_summary: "Customer claims TXN-9202 (2000 BDT to +8801812345678) was a wrong transfer, but history shows prior transfers to same recipient.",
      recommended_next_action: "Flag for human review. Verify if this was genuinely a wrong transfer given the established transaction pattern.",
      customer_reply: "We have received your request regarding transaction TXN-9202. Please do not share your PIN or OTP with anyone. Our dispute team will review the case carefully.",
      human_review_required: true,
      confidence: 0.75,
      reason_codes: ["wrong_transfer_claim", "evidence_inconsistent"],
    },
    rationale: "Repeated past transfers to the same recipient contradict the wrong transfer claim.",
  },
  {
    id: "SAMPLE-03",
    label: "Failed payment with balance deducted",
    input: {
      ticket_id: "TKT-003",
      complaint: "I tried to pay 1200 taka for my mobile recharge but the app showed failed. But my balance was deducted! Please refund my money.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9301", timestamp: "2026-04-14T16:00:00Z", type: "payment", amount: 1200, counterparty: "MERCHANT-MOBILE-OP", status: "failed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-003",
      relevant_transaction_id: "TXN-9301",
      evidence_verdict: "consistent",
      case_type: "payment_failed",
      severity: "high",
      department: "payments_ops",
      agent_summary: "Customer attempted a 1200 BDT mobile recharge (TXN-9301) which failed, but reports balance was deducted.",
      recommended_next_action: "Investigate TXN-9301 ledger status. If deducted on a failed payment, initiate reversal flow.",
      customer_reply: "We have noted that transaction TXN-9301 may have caused an unexpected balance deduction. Our payments team will review and any eligible amount will be returned through official channels. Please do not share your PIN or OTP with anyone.",
      human_review_required: false,
      confidence: 0.9,
      reason_codes: ["payment_failed", "potential_balance_deduction"],
    },
    rationale: "Clear payment failure with claimed balance deduction. Routes to payments_ops.",
  },
  {
    id: "SAMPLE-04",
    label: "Refund request requiring safe handling",
    input: {
      ticket_id: "TKT-004",
      complaint: "I paid 500 to a merchant for a product but I changed my mind and don't want it anymore. Please refund my 500 taka.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9401", timestamp: "2026-04-14T13:00:00Z", type: "payment", amount: 500, counterparty: "MERCHANT-7821", status: "completed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-004",
      relevant_transaction_id: "TXN-9401",
      evidence_verdict: "consistent",
      case_type: "refund_request",
      severity: "low",
      department: "customer_support",
      agent_summary: "Customer requests refund of 500 BDT for TXN-9401 due to change of mind.",
      recommended_next_action: "Inform the customer that refund eligibility depends on the merchant's policy.",
      customer_reply: "Thank you for reaching out. Refunds for completed merchant payments depend on the merchant's own policy. We recommend contacting the merchant directly. Please do not share your PIN or OTP with anyone.",
      human_review_required: false,
      confidence: 0.85,
      reason_codes: ["refund_request", "merchant_policy_dependent"],
    },
    rationale: "Service must NOT promise a refund. A response saying 'we will refund you' would trigger -10 penalty.",
  },
  {
    id: "SAMPLE-05",
    label: "Phishing or social engineering report",
    input: {
      ticket_id: "TKT-005",
      complaint: "Someone called me saying they are from bKash and asked for my OTP. They said my account will be blocked if I don't share it. Is this real? I haven't shared anything yet.",
      language: "en",
      channel: "call_center",
      user_type: "customer",
      transaction_history: [],
    },
    expected_output: {
      ticket_id: "TKT-005",
      relevant_transaction_id: null,
      evidence_verdict: "insufficient_data",
      case_type: "phishing_or_social_engineering",
      severity: "critical",
      department: "fraud_risk",
      agent_summary: "Customer reports an unsolicited call asking for OTP. Customer has not shared credentials.",
      recommended_next_action: "Escalate to fraud_risk team. Confirm company never asks for OTP.",
      customer_reply: "Thank you for reaching out before sharing any information. We never ask for your PIN, OTP, or password under any circumstances. Our fraud team has been notified.",
      human_review_required: true,
      confidence: 0.95,
      reason_codes: ["phishing", "credential_protection"],
    },
    rationale: "Phishing reports are critical by default. Empty transaction_history is normal for safety reports.",
  },
  {
    id: "SAMPLE-06",
    label: "Vague complaint, insufficient evidence",
    input: {
      ticket_id: "TKT-006",
      complaint: "Something is wrong with my money. Please check.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9601", timestamp: "2026-04-13T10:00:00Z", type: "cash_in", amount: 3000, counterparty: "AGENT-220", status: "completed" },
        { transaction_id: "TXN-9602", timestamp: "2026-04-12T15:30:00Z", type: "transfer", amount: 800, counterparty: "+8801911223344", status: "completed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-006",
      relevant_transaction_id: null,
      evidence_verdict: "insufficient_data",
      case_type: "other",
      severity: "low",
      department: "customer_support",
      agent_summary: "Customer reports a vague concern. Insufficient detail to identify any relevant transaction.",
      recommended_next_action: "Reply asking for specific transaction details, amount, and description of the issue.",
      customer_reply: "Thank you for reaching out. To help you faster, please share the transaction ID, amount, and a short description of what went wrong. Please do not share your PIN or OTP with anyone.",
      human_review_required: false,
      confidence: 0.6,
      reason_codes: ["vague_complaint", "needs_clarification"],
    },
    rationale: "Without specifics, service should not guess. Returns insufficient_data, asks for clarification.",
  },
  {
    id: "SAMPLE-07",
    label: "Agent cash-in issue, Bangla complaint",
    input: {
      ticket_id: "TKT-007",
      complaint: "আমি আজ সকালে এজেন্টের কাছে ২০০০ টাকা ক্যাশ ইন করেছি কিন্তু আমার ব্যালেন্সে টাকা আসেনি। এজেন্ট বলছে টাকা পাঠিয়েছে কিন্তু আমি দেখছি না।",
      language: "bn",
      channel: "call_center",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9701", timestamp: "2026-04-14T09:30:00Z", type: "cash_in", amount: 2000, counterparty: "AGENT-318", status: "pending" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-007",
      relevant_transaction_id: "TXN-9701",
      evidence_verdict: "consistent",
      case_type: "agent_cash_in_issue",
      severity: "high",
      department: "agent_operations",
      agent_summary: "Customer reports 2000 BDT cash-in via AGENT-318 not reflected in balance. Transaction is pending.",
      recommended_next_action: "Investigate TXN-9701 pending status with agent operations.",
      customer_reply: "আপনার লেনদেন TXN-9701 এর বিষয়ে আমরা অবগত হয়েছি। আমাদের এজেন্ট অপারেশন্স দল এটি দ্রুত যাচাই করবে। অনুগ্রহ করে কারো সাথে আপনার পিন বা ওটিপি শেয়ার করবেন না।",
      human_review_required: true,
      confidence: 0.88,
      reason_codes: ["agent_cash_in", "pending_transaction"],
    },
    rationale: "Bangla input handled natively. customer_reply in same language.",
  },
  {
    id: "SAMPLE-08",
    label: "Multiple plausible transactions, ambiguous match",
    input: {
      ticket_id: "TKT-008",
      complaint: "I sent 1000 to my brother yesterday but he says he didn't get it. Please check.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-9801", timestamp: "2026-04-13T11:20:00Z", type: "transfer", amount: 1000, counterparty: "+8801712001122", status: "completed" },
        { transaction_id: "TXN-9802", timestamp: "2026-04-13T19:45:00Z", type: "transfer", amount: 1000, counterparty: "+8801812334455", status: "completed" },
        { transaction_id: "TXN-9803", timestamp: "2026-04-13T20:10:00Z", type: "transfer", amount: 1000, counterparty: "+8801712001122", status: "failed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-008",
      relevant_transaction_id: null,
      evidence_verdict: "insufficient_data",
      case_type: "wrong_transfer",
      severity: "medium",
      department: "dispute_resolution",
      agent_summary: "Three 1000 BDT transfers exist to two recipients. Cannot determine which is the brother.",
      recommended_next_action: "Ask customer for the brother's number to identify the correct transaction.",
      customer_reply: "Thank you. We see multiple 1000 BDT transactions on that date. Could you share your brother's number? Please do not share your PIN or OTP with anyone.",
      human_review_required: false,
      confidence: 0.65,
      reason_codes: ["ambiguous_match", "needs_clarification"],
    },
    rationale: "Multiple plausible matches - don't guess. Return insufficient_data.",
  },
  {
    id: "SAMPLE-09",
    label: "Merchant settlement delay",
    input: {
      ticket_id: "TKT-009",
      complaint: "I am a merchant. My yesterday's sales of 15000 taka have not been settled to my account. Settlement usually happens by 11am next day.",
      language: "en",
      channel: "merchant_portal",
      user_type: "merchant",
      transaction_history: [
        { transaction_id: "TXN-9901", timestamp: "2026-04-13T18:00:00Z", type: "settlement", amount: 15000, counterparty: "MERCHANT-SELF", status: "pending" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-009",
      relevant_transaction_id: "TXN-9901",
      evidence_verdict: "consistent",
      case_type: "merchant_settlement_delay",
      severity: "medium",
      department: "merchant_operations",
      agent_summary: "Merchant reports 15000 BDT settlement (TXN-9901) delayed beyond standard next-day window.",
      recommended_next_action: "Route to merchant_operations to verify settlement batch status.",
      customer_reply: "We have noted your concern about settlement TXN-9901. Our merchant operations team will check and update you through official channels.",
      human_review_required: false,
      confidence: 0.92,
      reason_codes: ["merchant_settlement", "delay"],
    },
    rationale: "Merchant-side complaint, routes to merchant_operations. Response is business-formal.",
  },
  {
    id: "SAMPLE-10",
    label: "Duplicate payment claim",
    input: {
      ticket_id: "TKT-010",
      complaint: "I paid my electricity bill 850 taka but it deducted twice from my account. Please check, I only paid once.",
      language: "en",
      channel: "in_app_chat",
      user_type: "customer",
      transaction_history: [
        { transaction_id: "TXN-10001", timestamp: "2026-04-14T08:15:30Z", type: "payment", amount: 850, counterparty: "BILLER-DESCO", status: "completed" },
        { transaction_id: "TXN-10002", timestamp: "2026-04-14T08:15:42Z", type: "payment", amount: 850, counterparty: "BILLER-DESCO", status: "completed" },
      ],
    },
    expected_output: {
      ticket_id: "TKT-010",
      relevant_transaction_id: "TXN-10002",
      evidence_verdict: "consistent",
      case_type: "duplicate_payment",
      severity: "high",
      department: "payments_ops",
      agent_summary: "Two identical 850 BDT payments to BILLER-DESCO 12 seconds apart. Second is likely duplicate.",
      recommended_next_action: "Verify duplicate with payments_ops. If biller confirms single payment, initiate reversal.",
      customer_reply: "We have noted the possible duplicate payment for TXN-10002. Our payments team will verify and any eligible amount will be returned through official channels. Please do not share your PIN or OTP with anyone.",
      human_review_required: true,
      confidence: 0.93,
      reason_codes: ["duplicate_payment", "biller_verification_required"],
    },
    rationale: "Two identical payments 12 seconds apart indicate duplicate. relevant_transaction_id points to second transaction.",
  },
];
